ALTER TABLE "weekly_generation_job" DROP CONSTRAINT "weekly_generation_job_phase_check";--> statement-breakpoint
ALTER TABLE "weekly_generation_job" ADD COLUMN "slot_date" date;--> statement-breakpoint
ALTER TABLE "weekly_generation_job" ADD COLUMN "idempotency_key" uuid;--> statement-breakpoint
ALTER TABLE "weekly_generation_run" ADD COLUMN "pantry_fingerprint" varchar(43);--> statement-breakpoint
CREATE UNIQUE INDEX "weekly_generation_job_active_slot_key" ON "weekly_generation_job" USING btree ("run_id","slot_date") WHERE "weekly_generation_job"."phase" = 'slot_candidates' AND "weekly_generation_job"."status" IN ('queued', 'running');--> statement-breakpoint
CREATE UNIQUE INDEX "weekly_generation_job_household_idempotency_key" ON "weekly_generation_job" USING btree ("household_id","idempotency_key") WHERE "weekly_generation_job"."idempotency_key" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "weekly_generation_job_household_run_slot_idx" ON "weekly_generation_job" USING btree ("household_id","run_id","slot_date","created_at") WHERE "weekly_generation_job"."phase" = 'slot_candidates';--> statement-breakpoint
ALTER TABLE "weekly_generation_job" ADD CONSTRAINT "weekly_generation_job_slot_metadata_check" CHECK (("weekly_generation_job"."phase" = 'slot_candidates' AND "weekly_generation_job"."run_id" IS NOT NULL AND "weekly_generation_job"."slot_date" IS NOT NULL AND "weekly_generation_job"."idempotency_key" IS NOT NULL) OR ("weekly_generation_job"."phase" <> 'slot_candidates' AND "weekly_generation_job"."slot_date" IS NULL AND "weekly_generation_job"."idempotency_key" IS NULL));--> statement-breakpoint
ALTER TABLE "weekly_generation_job" ADD CONSTRAINT "weekly_generation_job_slot_week_check" CHECK ("weekly_generation_job"."slot_date" IS NULL OR ("weekly_generation_job"."slot_date" >= "weekly_generation_job"."week_start_date" AND "weekly_generation_job"."slot_date" < ("weekly_generation_job"."week_start_date" + 7)));--> statement-breakpoint
ALTER TABLE "weekly_generation_job" ADD CONSTRAINT "weekly_generation_job_phase_check" CHECK ("weekly_generation_job"."phase" IN ('candidates', 'instructions', 'slot_candidates'));--> statement-breakpoint
ALTER TABLE "weekly_generation_run" ADD CONSTRAINT "weekly_generation_run_pantry_fingerprint_check" CHECK ("weekly_generation_run"."pantry_fingerprint" IS NULL OR char_length("weekly_generation_run"."pantry_fingerprint") = 43);